export const USER_EMAIL_LOGIN_SUCCESS = 'user_email_login_success'
export const USER_EMAIL_LOGIN_FAIL = 'user_email_login_fail'
export const USER_EMAIL_LOGOUT_SUCCESS = 'user_email_logout_success'
export const USER_EMAIL_LOGOUT_FAIL = 'user_email_logout_fail'
export const OBTAIN_CURRENT_USER = 'obtain_current_user'
export const OBTAIN_CURRENT_USER_SUCCESS = 'obtain_current_user_success'
export const OBTAIN_CURRENT_USER_FAILURE = 'obtain_current_user_failure'
